# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Site settings
title: Escribo cosas
email: ivanheral@domain.com
description: "Blog sobre cine, linux, desarrollo y opiniones."
baseurl: "" # the subpath of your site, e.g. /blog
url: "ivanheral.github.io" # the base hostname & protocol for your site
twitter_username: ivanheral
github_username:  ivanheral
youtube_username:  ivanheral
# Build settings
markdown: kramdown
exclude: ['README.md', 'taskfile.js', 'imagemin.js', 'package.json', 'node_modules']